import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ModTool } from "@/components/ModTool";
import { PropProvider } from "@/components/PropProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className={cn(inter.className, "h-full")}>
        <PropProvider
          props={{
            primaryColor: "#617DCE",
            secondaryColor: "#1AC4CF",
            tertiaryColor: "#1B2544",
            lineHeight: "1.5",
            sectionGapPx: 20,

            header: {
              blockPadding: "1rem",
              sidePadding: "1rem",
              titleGap: "1rem",
              linksGap: "1rem",
            },

            hero: {
              titleGap: "1rem",
              titleFontSize: "2rem",
              lineHeight: "1.5",
              marginTop: "0",
            },

            cards: {
              padding: "1rem",
              lineHeight: "1.5",
              height: "200px",
              cardGap: "1rem",
              cardsGap: "1rem",
            },

            about: {
              gap: "1rem",
              titleFontSize: "2rem",
              lineHeight: "1.5",
            },

            bubbles: {
              bubbleGap: "1rem",
              bubblesGap: "1rem",

              bubble1Color: "#BA3963",
              bubble2Color: "#FFD600",
              bubble3Color: "#00EDA6",

              fontSize: "1rem",
            },

            footer: {
              gap: "1rem",
            },
          }}
        >
          {children}
          <ModTool />
        </PropProvider>
      </body>
    </html>
  );
}
