import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ModTool } from "@/components/ModTool";
import { PropProvider } from "@/components/PropProvider";
import { getDefaultProps } from "@/lib/default-props";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className={cn(inter.className, "h-full")}>
        <PropProvider props={getDefaultProps()}>
          {children}
          <ModTool />
        </PropProvider>
      </body>
    </html>
  );
}
